#![feature(test)]

// These benchmarks can be run from the project root with:
// > cargo bench --package mentat_tx_parser

extern crate test;
extern crate edn;
extern crate mentat_tx_parser;

use test::Bencher;
use mentat_tx_parser::Tx;

#[bench]
fn bench_parse1(b: &mut Bencher) {
    let input = r#"[[:db/add 1 :test/val "a"]]"#;
    let parsed_edn = edn::parse::value(input).expect("to parse test input");
    b.iter(|| Tx::parse(&parsed_edn));
}

#[bench]
fn bench_parse2(b: &mut Bencher) {
    let input = r#"
        [[:db/add 1  :test/val "a"]
         [:db/add 2  :test/val "b"]
         [:db/add 3  :test/val "c"]
         [:db/add 4  :test/val "d"]
         [:db/add 5  :test/val "e"]
         [:db/add 6  :test/val "f"]
         [:db/add 7  :test/val "g"]
         [:db/add 8  :test/val "h"]
         [:db/add 9  :test/val "i"]
         [:db/add 10 :test/val "j"]
         [:db/add 11 :test/val "k"]
         [:db/add 12 :test/val "l"]
         [:db/add 13 :test/val "m"]
         [:db/add 14 :test/val "n"]
         [:db/add 15 :test/val "o"]
         [:db/add 16 :test/val "p"]
         [:db/add 17 :test/val "q"]
         [:db/add 18 :test/val "r"]
         [:db/add 19 :test/val "s"]
         [:db/add 20 :test/val "t"]
         [:db/add 21 :test/val "u"]
         [:db/add 22 :test/val "v"]
         [:db/add 23 :test/val "w"]
         [:db/add 24 :test/val "x"]
         [:db/add 25 :test/val "y"]
         [:db/add 26 :test/val "z"]]"#;
    let parsed_edn = edn::parse::value(input).expect("to parse test input");
    b.iter(|| Tx::parse(&parsed_edn));
}

#[bench]
fn bench_parse3(b: &mut Bencher) {
    let input = r#"
        [[:db/add 1001 :test/val "a"]
         [:db/add 1002 :test/val "b"]
         [:db/add 1003 :test/val "c"]
         [:db/add 1004 :test/val "d"]
         [:db/add 1005 :test/val "e"]
         [:db/add 1006 :test/val "f"]
         [:db/add 1007 :test/val "g"]
         [:db/add 1008 :test/val "h"]
         [:db/add 1009 :test/val "i"]
         [:db/add 1010 :test/val "j"]
         [:db/add 1011 :test/val "k"]
         [:db/add 1012 :test/val "l"]
         [:db/add 1013 :test/val "m"]
         [:db/add 1014 :test/val "n"]
         [:db/add 1015 :test/val "o"]
         [:db/add 1016 :test/val "p"]
         [:db/add 1017 :test/val "q"]
         [:db/add 1018 :test/val "r"]
         [:db/add 1019 :test/val "s"]
         [:db/add 1020 :test/val "t"]
         [:db/add 1021 :test/val "u"]
         [:db/add 1022 :test/val "v"]
         [:db/add 1023 :test/val "w"]
         [:db/add 1024 :test/val "x"]
         [:db/add 1025 :test/val "y"]
         [:db/add 1026 :test/val "z"]
         [:db/add 1101 :test/val "A"]
         [:db/add 1102 :test/val "B"]
         [:db/add 1103 :test/val "C"]
         [:db/add 1104 :test/val "D"]
         [:db/add 1105 :test/val "E"]
         [:db/add 1106 :test/val "F"]
         [:db/add 1107 :test/val "G"]
         [:db/add 1108 :test/val "H"]
         [:db/add 1109 :test/val "I"]
         [:db/add 1110 :test/val "J"]
         [:db/add 1111 :test/val "K"]
         [:db/add 1112 :test/val "L"]
         [:db/add 1113 :test/val "M"]
         [:db/add 1114 :test/val "N"]
         [:db/add 1115 :test/val "O"]
         [:db/add 1116 :test/val "P"]
         [:db/add 1117 :test/val "Q"]
         [:db/add 1118 :test/val "R"]
         [:db/add 1119 :test/val "S"]
         [:db/add 1120 :test/val "T"]
         [:db/add 1121 :test/val "U"]
         [:db/add 1122 :test/val "V"]
         [:db/add 1123 :test/val "W"]
         [:db/add 1124 :test/val "X"]
         [:db/add 1125 :test/val "Y"]
         [:db/add 1126 :test/val "Z"]]"#;

    let parsed_edn = edn::parse::value(input).expect("to parse test input");
    b.iter(|| Tx::parse(&parsed_edn));
}

#[bench]
fn bench_parse4(b: &mut Bencher) {
    let input = r#"
        [[:db/add 1001 :test/val "a"]
         [:db/add 1002 :test/val "b"]
         [:db/add 1003 :test/val "c"]
         [:db/add 1004 :test/val "d"]
         [:db/add 1005 :test/val "e"]
         [:db/add 1006 :test/val "f"]
         [:db/add 1007 :test/val "g"]
         [:db/add 1008 :test/val "h"]
         [:db/add 1009 :test/val "i"]
         [:db/add 1010 :test/val "j"]
         [:db/add 1011 :test/val "k"]
         [:db/add 1012 :test/val "l"]
         [:db/add 1013 :test/val "m"]
         [:db/add 1014 :test/val "n"]
         [:db/add 1015 :test/val "o"]
         [:db/add 1016 :test/val "p"]
         [:db/add 1017 :test/val "q"]
         [:db/add 1018 :test/val "r"]
         [:db/add 1019 :test/val "s"]
         [:db/add 1020 :test/val "t"]
         [:db/add 1021 :test/val "u"]
         [:db/add 1022 :test/val "v"]
         [:db/add 1023 :test/val "w"]
         [:db/add 1024 :test/val "x"]
         [:db/add 1025 :test/val "y"]
         [:db/add 1026 :test/val "z"]
         [:db/add 1101 :test/val "A"]
         [:db/add 1102 :test/val "B"]
         [:db/add 1103 :test/val "C"]
         [:db/add 1104 :test/val "D"]
         [:db/add 1105 :test/val "E"]
         [:db/add 1106 :test/val "F"]
         [:db/add 1107 :test/val "G"]
         [:db/add 1108 :test/val "H"]
         [:db/add 1109 :test/val "I"]
         [:db/add 1110 :test/val "J"]
         [:db/add 1111 :test/val "K"]
         [:db/add 1112 :test/val "L"]
         [:db/add 1113 :test/val "M"]
         [:db/add 1114 :test/val "N"]
         [:db/add 1115 :test/val "O"]
         [:db/add 1116 :test/val "P"]
         [:db/add 1117 :test/val "Q"]
         [:db/add 1118 :test/val "R"]
         [:db/add 1119 :test/val "S"]
         [:db/add 1120 :test/val "T"]
         [:db/add 1121 :test/val "U"]
         [:db/add 1122 :test/val "V"]
         [:db/add 1123 :test/val "W"]
         [:db/add 1124 :test/val "X"]
         [:db/add 1125 :test/val "Y"]
         [:db/add 1126 :test/val "Z"]
         [:db/add 2001 :test/alt "a"]
         [:db/add 2002 :test/alt "b"]
         [:db/add 2003 :test/alt "c"]
         [:db/add 2004 :test/alt "d"]
         [:db/add 2005 :test/alt "e"]
         [:db/add 2006 :test/alt "f"]
         [:db/add 2007 :test/alt "g"]
         [:db/add 2008 :test/alt "h"]
         [:db/add 2009 :test/alt "i"]
         [:db/add 2010 :test/alt "j"]
         [:db/add 2011 :test/alt "k"]
         [:db/add 2012 :test/alt "l"]
         [:db/add 2013 :test/alt "m"]
         [:db/add 2014 :test/alt "n"]
         [:db/add 2015 :test/alt "o"]
         [:db/add 2016 :test/alt "p"]
         [:db/add 2017 :test/alt "q"]
         [:db/add 2018 :test/alt "r"]
         [:db/add 2019 :test/alt "s"]
         [:db/add 2020 :test/alt "t"]
         [:db/add 2021 :test/alt "u"]
         [:db/add 2022 :test/alt "v"]
         [:db/add 2023 :test/alt "w"]
         [:db/add 2024 :test/alt "x"]
         [:db/add 2025 :test/alt "y"]
         [:db/add 2026 :test/alt "z"]
         [:db/add 2101 :test/alt "A"]
         [:db/add 2102 :test/alt "B"]
         [:db/add 2103 :test/alt "C"]
         [:db/add 2104 :test/alt "D"]
         [:db/add 2105 :test/alt "E"]
         [:db/add 2106 :test/alt "F"]
         [:db/add 2107 :test/alt "G"]
         [:db/add 2108 :test/alt "H"]
         [:db/add 2109 :test/alt "I"]
         [:db/add 2110 :test/alt "J"]
         [:db/add 2111 :test/alt "K"]
         [:db/add 2112 :test/alt "L"]
         [:db/add 2113 :test/alt "M"]
         [:db/add 2114 :test/alt "N"]
         [:db/add 2115 :test/alt "O"]
         [:db/add 2116 :test/alt "P"]
         [:db/add 2117 :test/alt "Q"]
         [:db/add 2118 :test/alt "R"]
         [:db/add 2119 :test/alt "S"]
         [:db/add 2120 :test/alt "T"]
         [:db/add 2121 :test/alt "U"]
         [:db/add 2122 :test/alt "V"]
         [:db/add 2123 :test/alt "W"]
         [:db/add 2124 :test/alt "X"]
         [:db/add 2125 :test/alt "Y"]
         [:db/add 2126 :test/alt "Z"]]"#;

    let parsed_edn = edn::parse::value(input).expect("to parse test input");
    b.iter(|| Tx::parse(&parsed_edn));
}
